
USE TFG;

INSERT INTO estado (nome, uf) VALUES
('Acre', 'AC'),
('Alagoas', 'AL'),
('Amapá', 'AP'),
('Amazonas', 'AM'),
('Bahia', 'BA'),
('Ceará', 'CE'),
('Distrito Federal', 'DF'),
('Espírito Santo', 'ES'),
('Goiás', 'GO'),
('Maranhão', 'MA'),
('Mato Grosso', 'MT'),
('Mato Grosso do Sul', 'MS'),
('Minas Gerais', 'MG'),
('Pará', 'PA'),
('Paraíba', 'PB'),
('Paraná', 'PR'),
('Pernambuco', 'PE'),
('Piauí', 'PI'),
('Rio de Janeiro', 'RJ'),
('Rio Grande do Norte', 'RN'),
('Rio Grande do Sul', 'RS'),
('Rondônia', 'RO'),
('Roraima', 'RR'),
('Santa Catarina', 'SC'),
('São Paulo', 'SP'),
('Sergipe', 'SE'),
('Tocantins', 'TO');


INSERT INTO cidade (nome, estado_id) VALUES
('Acrelândia', 1),
('Assis Brasil', 1),
('Brasiléia', 1),
('Bujari', 1),
('Capixaba', 1),
('Cruzeiro do Sul', 1),
('Epitaciolândia', 1),
('Feijó', 1),
('Jordão', 1),
('Mâncio Lima', 1),
('Manoel Urbano', 1),
('Marechal Thaumaturgo', 1),
('Plácido de Castro', 1),
('Porto Acre', 1),
('Porto Walter', 1),
('Rio Branco', 1),
('Rodrigues Alves', 1),
('Santa Rosa do Purus', 1),
('Sena Madureira', 1),
('Senador Guiomard', 1),
('Tarauacá', 1),
('Xapuri', 1);

INSERT INTO cidade (nome, estado_id) VALUES
('Água Branca', 2),
('Anadia', 2),
('Arapiraca', 2),
('Atalaia', 2),
('Barra de Santo Antônio', 2),
('Barra de São Miguel', 2),
('Batalha', 2),
('Belém', 2),
('Belo Monte', 2),
('Boca da Mata', 2),
('Branquinha', 2),
('Cacimbinhas', 2),
('Cajueiro', 2),
('Campestre', 2),
('Campo Alegre', 2),
('Campo Grande', 2),
('Canapi', 2),
('Capela', 2),
('Carneiros', 2),
('Chã Preta', 2),
('Coité do Nóia', 2),
('Colônia Leopoldina', 2),
('Coqueiro Seco', 2),
('Coruripe', 2),
('Craíbas', 2),
('Delmiro Gouveia', 2),
('Dois Riachos', 2),
('Estrela de Alagoas', 2),
('Feira Grande', 2),
('Feliz Deserto', 2),
('Flexeiras', 2),
('Girau do Ponciano', 2),
('Ibateguara', 2),
('Igaci', 2),
('Igreja Nova', 2),
('Inhapi', 2),
('Jacaré dos Homens', 2),
('Jacuípe', 2),
('Japaratinga', 2),
('Jaramataia', 2),
('Jequiá da Praia', 2),
('Joaquim Gomes', 2),
('Jundiá', 2),
('Junqueiro', 2),
('Lagoa da Canoa', 2),
('Limoeiro de Anadia', 2),
('Maceió', 2),
('Major Isidoro', 2),
('Mar Vermelho', 2),
('Maragogi', 2),
('Maravilha', 2),
('Marechal Deodoro', 2),
('Maribondo', 2),
('Mata Grande', 2),
('Matriz de Camaragibe', 2),
('Messias', 2),
('Minador do Negrão', 2),
('Monteirópolis', 2),
('Murici', 2),
('Novo Lino', 2),
('Olho d\'Água das Flores', 2),
('Olho d\'Água do Casado', 2),
('Olho d\'Água Grande', 2),
('Olivença', 2),
('Ouro Branco', 2),
('Palestina', 2),
('Palmeira dos Índios', 2),
('Pão de Açúcar', 2),
('Pariconha', 2),
('Paripueira', 2),
('Passo de Camaragibe', 2),
('Paulo Jacinto', 2),
('Penedo', 2),
('Piaçabuçu', 2),
('Pilar', 2),
('Pindoba', 2),
('Piranhas', 2),
('Poço das Trincheiras', 2),
('Porto Calvo', 2),
('Porto de Pedras', 2),
('Porto Real do Colégio', 2),
('Quebrangulo', 2),
('Rio Largo', 2),
('Roteiro', 2),
('Santa Luzia do Norte', 2),
('Santana do Ipanema', 2),
('Santana do Mundaú', 2),
('São Brás', 2),
('São José da Laje', 2),
('São José da Tapera', 2),
('São Luís do Quitunde', 2),
('São Miguel dos Campos', 2),
('São Miguel dos Milagres', 2),
('São Sebastião', 2),
('Satuba', 2),
('Senador Rui Palmeira', 2),
('Tanque d\'Arca', 2),
('Taquarana', 2),
('Teotônio Vilela', 2),
('Traipu', 2),
('União dos Palmares', 2),
('Viçosa', 2);

INSERT INTO cidade (nome, estado_id) VALUES
('Amapá', 3),
('Calçoene', 3),
('Cutias', 3),
('Ferreira Gomes', 3),
('Itaubal', 3),
('Laranjal do Jari', 3),
('Macapá', 3),
('Mazagão', 3),
('Oiapoque', 3),
('Pedra Branca do Amapari', 3),
('Porto Grande', 3),
('Pracuúba', 3),
('Santana', 3),
('Serra do Navio', 3),
('Tartarugalzinho', 3),
('Vitória do Jari', 3);

INSERT INTO cidade (nome, estado_id) VALUES
('Alvarães', 4),
('Amaturá', 4),
('Anamã', 4),
('Anori', 4),
('Apuí', 4),
('Atalaia do Norte', 4),
('Autazes', 4),
('Barcelos', 4),
('Barreirinha', 4),
('Benjamin Constant', 4),
('Beruri', 4),
('Boa Vista do Ramos', 4),
('Boca do Acre', 4),
('Borba', 4),
('Caapiranga', 4),
('Canutama', 4),
('Carauari', 4),
('Careiro', 4),
('Careiro da Várzea', 4),
('Coari', 4),
('Codajás', 4),
('Eirunepé', 4),
('Envira', 4),
('Fonte Boa', 4),
('Guajará', 4),
('Humaitá', 4),
('Ipixuna', 4),
('Iranduba', 4),
('Itacoatiara', 4),
('Itamarati', 4),
('Itapiranga', 4),
('Japurá', 4),
('Juruá', 4),
('Jutaí', 4),
('Lábrea', 4),
('Manacapuru', 4),
('Manaquiri', 4),
('Manaus', 4),
('Manicoré', 4),
('Maraã', 4),
('Maués', 4),
('Nhamundá', 4),
('Nova Olinda do Norte', 4),
('Novo Airão', 4),
('Novo Aripuanã', 4),
('Parintins', 4),
('Pauini', 4),
('Presidente Figueiredo', 4),
('Rio Preto da Eva', 4),
('Santa Isabel do Rio Negro', 4),
('Santo Antônio do Içá', 4),
('São Gabriel da Cachoeira', 4),
('São Paulo de Olivença', 4),
('São Sebastião do Uatumã', 4),
('Silves', 4),
('Tabatinga', 4),
('Tapauá', 4),
('Tefé', 4),
('Tonantins', 4),
('Uarini', 4),
('Urucará', 4),
('Urucurituba', 4);

INSERT INTO cidade (nome, estado_id) VALUES
('Abaíra', 5),
('Abaré', 5),
('Acajutiba', 5),
('Adustina', 5),
('Água Fria', 5),
('Aiquara', 5),
('Alagoinhas', 5),
('Alcobaça', 5),
('Almadina', 5),
('Amargosa', 5),
('Amélia Rodrigues', 5),
('América Dourada', 5),
('Anagé', 5),
('Andaraí', 5),
('Andorinha', 5),
('Angical', 5),
('Anguera', 5),
('Antas', 5),
('Antônio Cardoso', 5),
('Antônio Gonçalves', 5),
('Aporá', 5),
('Apuarema', 5),
('Araças', 5),
('Aracatu', 5),
('Araci', 5),
('Aramari', 5),
('Arataca', 5),
('Aratuípe', 5),
('Aurelino Leal', 5),
('Baianópolis', 5),
('Baixa Grande', 5),
('Banzaê', 5),
('Barra', 5),
('Barra da Estiva', 5),
('Barra do Choça', 5),
('Barra do Mendes', 5),
('Barra do Rocha', 5),
('Barreiras', 5),
('Barro Alto', 5),
('Barrocas', 5),
('Barro Preto', 5),
('Belmonte', 5),
('Belo Campo', 5),
('Biritinga', 5),
('Boa Nova', 5),
('Boa Vista do Tupim', 5),
('Bom Jesus da Lapa', 5),
('Bom Jesus da Serra', 5),
('Boninal', 5),
('Bonito', 5),
('Boquira', 5),
('Botuporã', 5),
('Brejões', 5),
('Brejolândia', 5),
('Brotas de Macaúbas', 5),
('Brumado', 5),
('Buerarema', 5),
('Buritirama', 5),
('Caatiba', 5),
('Cabaceiras do Paraguaçu', 5),
('Cachoeira', 5),
('Caculé', 5),
('Caém', 5),
('Caetanos', 5),
('Caetité', 5),
('Cafarnaum', 5),
('Cairu', 5),
('Caldeirão Grande', 5),
('Camacan', 5),
('Camaçari', 5),
('Camamu', 5),
('Campo Alegre de Lourdes', 5),
('Campo Formoso', 5),
('Canápolis', 5),
('Canarana', 5),
('Canavieiras', 5),
('Candeal', 5),
('Candeias', 5),
('Candiba', 5),
('Cândido Sales', 5),
('Cansanção', 5),
('Canudos', 5),
('Capela do Alto Alegre', 5),
('Capim Grosso', 5),
('Caraíbas', 5),
('Caravelas', 5),
('Cardeal da Silva', 5),
('Carinhanha', 5),
('Casa Nova', 5),
('Castro Alves', 5),
('Catolândia', 5),
('Catu', 5),
('Caturama', 5),
('Central', 5),
('Chorrochó', 5),
('Cícero Dantas', 5),
('Cipó', 5),
('Coaraci', 5),
('Cocos', 5),
('Conceição da Feira', 5),
('Conceição do Almeida', 5),
('Conceição do Coité', 5),
('Conceição do Jacuípe', 5),
('Conde', 5),
('Condeúba', 5),
('Contendas do Sincorá', 5),
('Coração de Maria', 5),
('Cordeiros', 5),
('Coribe', 5),
('Coronel João Sá', 5),
('Correntina', 5),
('Cotegipe', 5),
('Cravolândia', 5),
('Crisópolis', 5),
('Cristópolis', 5),
('Cruz das Almas', 5),
('Curaçá', 5),
('Dário Meira', 5),
('Dias d\'Ávila', 5),
('Dom Basílio', 5),
('Dom Macedo Costa', 5),
('Elísio Medrado', 5),
('Encruzilhada', 5),
('Entre Rios', 5),
('Érico Cardoso', 5),
('Esplanada', 5),
('Euclides da Cunha', 5),
('Eunápolis', 5),
('Fátima', 5),
('Feira da Mata', 5),
('Feira de Santana', 5),
('Filadélfia', 5),
('Firmino Alves', 5),
('Floresta Azul', 5),
('Formosa do Rio Preto', 5),
('Gandu', 5),
('Gavião', 5),
('Gentio do Ouro', 5),
('Glória', 5),
('Gongogi', 5),
('Governador Mangabeira', 5),
('Guajeru', 5),
('Guanambi', 5),
('Guaratinga', 5),
('Heliópolis', 5),
('Iaçu', 5),
('Ibiassucê', 5),
('Ibicaraí', 5),
('Ibicoara', 5),
('Ibicuí', 5),
('Ibipeba', 5),
('Ibipitanga', 5),
('Ibiquera', 5),
('Ibirapitanga', 5),
('Ibirapuã', 5),
('Ibirataia', 5),
('Ibitiara', 5),
('Ibititá', 5),
('Ibotirama', 5),
('Ichu', 5),
('Igaporã', 5),
('Igrapiúna', 5),
('Iguaí', 5),
('Ilhéus', 5),
('Inhambupe', 5),
('Ipecaetá', 5),
('Ipiaú', 5),
('Ipirá', 5),
('Ipupiara', 5),
('Irajuba', 5),
('Iramaia', 5),
('Iraquara', 5),
('Irará', 5),
('Irecê', 5),
('Itabela', 5),
('Itaberaba', 5),
('Itabuna', 5),
('Itacaré', 5),
('Itaeté', 5),
('Itagi', 5),
('Itagibá', 5),
('Itagimirim', 5),
('Itaguaçu da Bahia', 5),
('Itaju do Colônia', 5),
('Itajuípe', 5),
('Itamaraju', 5),
('Itamari', 5),
('Itambé', 5),
('Itanagra', 5),
('Itanhém', 5),
('Itaparica', 5),
('Itapé', 5),
('Itapebi', 5),
('Itapetinga', 5),
('Itapicuru', 5),
('Itapitanga', 5),
('Itaquara', 5),
('Itarantim', 5),
('Itatim', 5),
('Itiruçu', 5),
('Itiúba', 5),
('Itororó', 5),
('Ituaçu', 5),
('Ituberá', 5),
('Iuiú', 5),
('Jaborandi', 5),
('Jacaraci', 5),
('Jacobina', 5),
('Jaguaquara', 5),
('Jaguarari', 5),
('Jaguaripe', 5),
('Jandaíra', 5),
('Jequié', 5),
('Jeremoabo', 5),
('Jiquiriçá', 5),
('Jitaúna', 5),
('João Dourado', 5),
('Juazeiro', 5),
('Jucuruçu', 5),
('Jussara', 5),
('Jussari', 5),
('Jussiape', 5),
('Lafaiete Coutinho', 5),
('Lagoa Real', 5),
('Laje', 5),
('Lajedão', 5),
('Lajedinho', 5),
('Lajedo do Tabocal', 5),
('Lamarão', 5),
('Lapão', 5),
('Lauro de Freitas', 5),
('Lençóis', 5),
('Licínio de Almeida', 5),
('Livramento de Nossa Senhora', 5),
('Luís Eduardo Magalhães', 5),
('Macajuba', 5),
('Macarani', 5),
('Macaúbas', 5),
('Macururé', 5),
('Madre de Deus', 5),
('Maetinga', 5),
('Maiquinique', 5),
('Mairi', 5),
('Malhada', 5),
('Malhada de Pedras', 5),
('Manoel Vitorino', 5),
('Mansidão', 5),
('Maracás', 5),
('Maragogipe', 5),
('Maraú', 5),
('Marcionílio Souza', 5),
('Mascote', 5),
('Mata de São João', 5),
('Matina', 5),
('Medeiros Neto', 5),
('Miguel Calmon', 5),
('Milagres', 5),
('Mirangaba', 5),
('Mirante', 5),
('Monte Santo', 5),
('Morpará', 5),
('Morro do Chapéu', 5),
('Mortugaba', 5),
('Mucugê', 5),
('Mucuri', 5),
('Mulungu do Morro', 5),
('Mundo Novo', 5),
('Muniz Ferreira', 5),
('Muquém de São Francisco', 5),
('Muritiba', 5),
('Mutuípe', 5),
('Nazaré', 5),
('Nilo Peçanha', 5),
('Nordestina', 5),
('Nova Canaã', 5),
('Nova Fátima', 5),
('Nova Ibiá', 5),
('Nova Itarana', 5),
('Nova Redenção', 5),
('Nova Soure', 5),
('Nova Viçosa', 5),
('Novo Horizonte', 5),
('Novo Triunfo', 5),
('Olindina', 5),
('Oliveira dos Brejinhos', 5),
('Ouriçangas', 5),
('Ourolândia', 5),
('Palmas de Monte Alto', 5),
('Palmeiras', 5),
('Paramirim', 5),
('Paratinga', 5),
('Paripiranga', 5),
('Pau Brasil', 5),
('Paulo Afonso', 5),
('Pé de Serra', 5),
('Pedrão', 5),
('Pedro Alexandre', 5),
('Piatã', 5),
('Pilão Arcado', 5),
('Pindaí', 5),
('Pindobaçu', 5),
('Pintadas', 5),
('Piraí do Norte', 5),
('Piripá', 5),
('Piritiba', 5),
('Planaltino', 5),
('Planalto', 5),
('Poções', 5),
('Pojuca', 5),
('Ponto Novo', 5),
('Porto Seguro', 5),
('Potiraguá', 5),
('Prado', 5),
('Presidente Dutra', 5),
('Presidente Jânio Quadros', 5),
('Presidente Tancredo Neves', 5),
('Queimadas', 5),
('Quijingue', 5),
('Quixabeira', 5),
('Rafael Jambeiro', 5),
('Remanso', 5),
('Retirolândia', 5),
('Riachão das Neves', 5),
('Riachão do Jacuípe', 5),
('Riacho de Santana', 5),
('Ribeira do Amparo', 5),
('Ribeira do Pombal', 5),
('Ribeirão do Largo', 5),
('Rio de Contas', 5),
('Rio do Antônio', 5),
('Rio do Pires', 5),
('Rio Real', 5),
('Rodelas', 5),
('Ruy Barbosa', 5),
('Salinas da Margarida', 5),
('Salvador', 5),
('Santa Bárbara', 5),
('Santa Brígida', 5),
('Santa Cruz Cabrália', 5),
('Santa Cruz da Vitória', 5),
('Santa Inês', 5),
('Santa Luzia', 5),
('Santa Maria da Vitória', 5),
('Santa Rita de Cássia', 5),
('Santa Teresinha', 5),
('Santaluz', 5),
('Santana', 5),
('Santanópolis', 5),
('Santo Amaro', 5),
('Santo Antônio de Jesus', 5),
('Santo Estêvão', 5),
('São Desidério', 5),
('São Domingos', 5),
('São Felipe', 5),
('São Félix', 5),
('São Félix do Coribe', 5),
('São Francisco do Conde', 5),
('São Gabriel', 5),
('São Gonçalo dos Campos', 5),
('São José da Vitória', 5),
('São José do Jacuípe', 5),
('São Miguel das Matas', 5),
('São Sebastião do Passé', 5),
('Sapeaçu', 5),
('Sátiro Dias', 5),
('Saubara', 5),
('Saúde', 5),
('Seabra', 5),
('Sebastião Laranjeiras', 5),
('Senhor do Bonfim', 5),
('Sento Sé', 5),
('Serra do Ramalho', 5),
('Serra Dourada', 5),
('Serra Preta', 5),
('Serrinha', 5),
('Serrolândia', 5),
('Simões Filho', 5),
('Sítio do Mato', 5),
('Sítio do Quinto', 5),
('Sobradinho', 5),
('Souto Soares', 5),
('Tabocas do Brejo Velho', 5),
('Tanhaçu', 5),
('Tanque Novo', 5),
('Tanquinho', 5),
('Taperoá', 5),
('Tapiramutá', 5),
('Teixeira de Freitas', 5),
('Teodoro Sampaio', 5),
('Teofilândia', 5),
('Teolândia', 5),
('Terra Nova', 5),
('Tremedal', 5),
('Tucano', 5),
('Uauá', 5),
('Ubaíra', 5),
('Ubaitaba', 5),
('Ubatã', 5),
('Uibaí', 5),
('Umburanas', 5),
('Una', 5),
('Urandi', 5),
('Uruçuca', 5),
('Utinga', 5),
('Valença', 5),
('Valente', 5),
('Várzea da Roça', 5),
('Várzea do Poço', 5),
('Várzea Nova', 5),
('Varzedo', 5),
('Vera Cruz', 5),
('Vereda', 5),
('Vitória da Conquista', 5),
('Wagner', 5),
('Wanderley', 5),
('Wenceslau Guimarães', 5),
('Xique-Xique', 5);

INSERT INTO cidade (nome, estado_id) VALUES
('Abaiara', 6),
('Acarape', 6),
('Acaraú', 6),
('Acopiara', 6),
('Aiuaba', 6),
('Alcântaras', 6),
('Altaneira', 6),
('Alto Santo', 6),
('Amontada', 6),
('Antonina do Norte', 6),
('Apuiarés', 6),
('Aquiraz', 6),
('Aracati', 6),
('Aracoiaba', 6),
('Ararendá', 6),
('Araripe', 6),
('Aratuba', 6),
('Arneiroz', 6),
('Assaré', 6),
('Aurora', 6),
('Baixio', 6),
('Banabuiú', 6),
('Barbalha', 6),
('Barreira', 6),
('Barro', 6),
('Barroquinha', 6),
('Baturité', 6),
('Beberibe', 6),
('Bela Cruz', 6),
('Boa Viagem', 6),
('Brejo Santo', 6),
('Camocim', 6),
('Campos Sales', 6),
('Canindé', 6),
('Capistrano', 6),
('Caridade', 6),
('Cariré', 6),
('Caririaçu', 6),
('Cariús', 6),
('Carnaubal', 6),
('Cascavel', 6),
('Catarina', 6),
('Catunda', 6),
('Caucaia', 6),
('Cedro', 6),
('Chaval', 6),
('Choró', 6),
('Chorozinho', 6),
('Coreaú', 6),
('Crateús', 6),
('Crato', 6),
('Croatá', 6),
('Cruz', 6),
('Deputado Irapuan Pinheiro', 6),
('Ereré', 6),
('Eusébio', 6),
('Farias Brito', 6),
('Forquilha', 6),
('Fortaleza', 6),
('Fortim', 6),
('Frecheirinha', 6),
('General Sampaio', 6),
('Graça', 6),
('Granja', 6),
('Granjeiro', 6),
('Groaíras', 6),
('Guaiúba', 6),
('Guaraciaba do Norte', 6),
('Guaramiranga', 6),
('Hidrolândia', 6),
('Horizonte', 6),
('Ibaretama', 6),
('Ibiapina', 6),
('Ibicuitinga', 6),
('Icapuí', 6),
('Icó', 6),
('Iguatu', 6),
('Independência', 6),
('Ipaporanga', 6),
('Ipaumirim', 6),
('Ipu', 6),
('Ipueiras', 6),
('Iracema', 6),
('Irauçuba', 6),
('Itaiçaba', 6),
('Itaitinga', 6),
('Itapagé', 6),
('Itapipoca', 6),
('Itapiúna', 6),
('Itarema', 6),
('Itatira', 6),
('Jaguaretama', 6),
('Jaguaribara', 6),
('Jaguaribe', 6),
('Jaguaruana', 6),
('Jardim', 6),
('Jati', 6),
('Jijoca de Jericoacoara', 6),
('Juazeiro do Norte', 6),
('Jucás', 6),
('Lavras da Mangabeira', 6),
('Limoeiro do Norte', 6),
('Madalena', 6),
('Maracanaú', 6),
('Maranguape', 6),
('Marco', 6),
('Martinópole', 6),
('Massapê', 6),
('Mauriti', 6),
('Meruoca', 6),
('Milagres', 6),
('Milhã', 6),
('Miraíma', 6),
('Missão Velha', 6),
('Mombaça', 6),
('Monsenhor Tabosa', 6),
('Morada Nova', 6),
('Moraújo', 6),
('Morrinhos', 6),
('Mucambo', 6),
('Mulungu', 6),
('Nova Olinda', 6),
('Nova Russas', 6),
('Novo Oriente', 6),
('Ocara', 6),
('Orós', 6),
('Pacajus', 6),
('Pacatuba', 6),
('Pacoti', 6),
('Pacujá', 6),
('Palhano', 6),
('Palmácia', 6),
('Paracuru', 6),
('Paraipaba', 6),
('Parambu', 6),
('Paramoti', 6),
('Pedra Branca', 6),
('Penaforte', 6),
('Pentecoste', 6),
('Pereiro', 6),
('Pindoretama', 6),
('Piquet Carneiro', 6),
('Pires Ferreira', 6),
('Poranga', 6),
('Porteiras', 6),
('Potengi', 6),
('Potiretama', 6),
('Quiterianópolis', 6),
('Quixadá', 6),
('Quixelô', 6),
('Quixeramobim', 6),
('Quixeré', 6),
('Redenção', 6),
('Reriutaba', 6),
('Russas', 6),
('Saboeiro', 6),
('Salitre', 6),
('Santa Quitéria', 6),
('Santana do Acaraú', 6),
('Santana do Cariri', 6),
('São Benedito', 6),
('São Gonçalo do Amarante', 6),
('São João do Jaguaribe', 6),
('São Luís do Curu', 6),
('Senador Pompeu', 6),
('Senador Sá', 6),
('Sobral', 6),
('Solonópole', 6),
('Tabuleiro do Norte', 6),
('Tamboril', 6),
('Tarrafas', 6),
('Tauá', 6),
('Tejuçuoca', 6),
('Tianguá', 6),
('Trairi', 6),
('Tururu', 6),
('Ubajara', 6),
('Umari', 6),
('Umirim', 6),
('Uruburetama', 6),
('Uruoca', 6),
('Varjota', 6),
('Várzea Alegre', 6),
('Viçosa do Ceará', 6);

INSERT INTO cidade (nome, estado_id) VALUES
('Afonso Cláudio', 7),
('Água Doce do Norte', 7),
('Águia Branca', 7),
('Alegre', 7),
('Alfredo Chaves', 7),
('Alto Rio Novo', 7),
('Anchieta', 7),
('Apiacá', 7),
('Aracruz', 7),
('Atilio Vivacqua', 7),
('Baixo Guandu', 7),
('Barra de São Francisco', 7),
('Boa Esperança', 7),
('Bom Jesus do Norte', 7),
('Brejetuba', 7),
('Cachoeiro de Itapemirim', 7),
('Cariacica', 7),
('Castelo', 7),
('Colatina', 7),
('Conceição da Barra', 7),
('Conceição do Castelo', 7),
('Divino de São Lourenço', 7),
('Domingos Martins', 7),
('Dores do Rio Preto', 7),
('Ecoporanga', 7),
('Fundão', 7),
('Governador Lindenberg', 7),
('Guaçuí', 7),
('Guarapari', 7),
('Ibatiba', 7),
('Ibiraçu', 7),
('Ibitirama', 7),
('Iconha', 7),
('Irupi', 7),
('Itaguaçu', 7),
('Itapemirim', 7),
('Itarana', 7),
('Iúna', 7),
('Jaguaré', 7),
('Jerônimo Monteiro', 7),
('João Neiva', 7),
('Laranja da Terra', 7),
('Linhares', 7),
('Mantenópolis', 7),
('Marataízes', 7),
('Marechal Floriano', 7),
('Marilândia', 7),
('Mimoso do Sul', 7),
('Montanha', 7),
('Mucurici', 7),
('Muniz Freire', 7),
('Muqui', 7),
('Nova Venécia', 7),
('Pancas', 7),
('Pedro Canário', 7),
('Pinheiros', 7),
('Piúma', 7),
('Ponto Belo', 7),
('Presidente Kennedy', 7),
('Rio Bananal', 7),
('Rio Novo do Sul', 7),
('Santa Leopoldina', 7),
('Santa Maria de Jetibá', 7),
('Santa Teresa', 7),
('São Domingos do Norte', 7),
('São Gabriel da Palha', 7),
('São José do Calçado', 7),
('São Mateus', 7),
('São Roque do Canaã', 7),
('Serra', 7),
('Sooretama', 7),
('Vargem Alta', 7),
('Venda Nova do Imigrante', 7),
('Viana', 7),
('Vila Pavão', 7),
('Vila Valério', 7),
('Vila Velha', 7),
('Vitória', 7);

INSERT INTO cidade (nome, estado_id) VALUES
('Abadia de Goiás', 8),
('Abadiânia', 8),
('Acreúna', 8),
('Adelândia', 8),
('Água Fria de Goiás', 8),
('Água Limpa', 8),
('Águas Lindas de Goiás', 8),
('Alexânia', 8),
('Aloândia', 8),
('Alto Horizonte', 8),
('Alto Paraíso de Goiás', 8),
('Alvorada do Norte', 8),
('Amaralina', 8),
('Americano do Brasil', 8),
('Amorinópolis', 8),
('Anápolis', 8),
('Anhanguera', 8),
('Anicuns', 8),
('Aparecida de Goiânia', 8),
('Aparecida do Rio Doce', 8),
('Aporé', 8),
('Araçu', 8),
('Aragarças', 8),
('Aragoiânia', 8),
('Araguapaz', 8),
('Arenópolis', 8),
('Aruanã', 8),
('Aurilândia', 8),
('Avelinópolis', 8),
('Baliza', 8),
('Barro Alto', 8),
('Bela Vista de Goiás', 8),
('Bom Jardim de Goiás', 8),
('Bom Jesus de Goiás', 8),
('Bonfinópolis', 8),
('Bonópolis', 8),
('Brazabrantes', 8),
('Britânia', 8),
('Buriti Alegre', 8),
('Buriti de Goiás', 8),
('Buritinópolis', 8),
('Cabeceiras', 8),
('Cachoeira Alta', 8),
('Cachoeira de Goiás', 8),
('Cachoeira Dourada', 8),
('Caçu', 8),
('Caiapônia', 8),
('Caldas Novas', 8),
('Caldazinha', 8),
('Campestre de Goiás', 8),
('Campinaçu', 8),
('Campinorte', 8),
('Campo Alegre de Goiás', 8),
('Campo Limpo de Goiás', 8),
('Campos Belos', 8),
('Campos Verdes', 8),
('Carmo do Rio Verde', 8),
('Castelândia', 8),
('Catalão', 8),
('Caturaí', 8),
('Cavalcante', 8),
('Ceres', 8),
('Cezarina', 8),
('Chapadão do Céu', 8),
('Cidade Ocidental', 8),
('Cocalzinho de Goiás', 8),
('Colinas do Sul', 8),
('Córrego do Ouro', 8),
('Corumbá de Goiás', 8),
('Corumbaíba', 8),
('Cristalina', 8),
('Cristianópolis', 8),
('Crixás', 8),
('Cromínia', 8),
('Cumari', 8),
('Damianópolis', 8),
('Damolândia', 8),
('Davinópolis', 8),
('Diorama', 8),
('Divinópolis de Goiás', 8),
('Doverlândia', 8),
('Edealina', 8),
('Edéia', 8),
('Estrela do Norte', 8),
('Faina', 8),
('Fazenda Nova', 8),
('Firminópolis', 8),
('Flores de Goiás', 8),
('Formosa', 8),
('Formoso', 8),
('Gameleira de Goiás', 8),
('Goianápolis', 8),
('Goiandira', 8),
('Goianésia', 8),
('Goiânia', 8),
('Goianira', 8),
('Goiás', 8),
('Goiatuba', 8),
('Gouvelândia', 8),
('Guapó', 8),
('Guaraíta', 8),
('Guarani de Goiás', 8),
('Guarinos', 8),
('Heitoraí', 8),
('Hidrolândia', 8),
('Hidrolina', 8),
('Iaciara', 8),
('Inaciolândia', 8),
('Indiara', 8),
('Inhumas', 8),
('Ipameri', 8),
('Ipiranga de Goiás', 8),
('Iporá', 8),
('Israelândia', 8),
('Itaberaí', 8),
('Itaguari', 8),
('Itaguaru', 8),
('Itajá', 8),
('Itapaci', 8),
('Itapirapuã', 8),
('Itapuranga', 8),
('Itarumã', 8),
('Itauçu', 8),
('Itumbiara', 8),
('Ivolândia', 8),
('Jandaia', 8),
('Jaraguá', 8),
('Jataí', 8),
('Jaupaci', 8),
('Jesúpolis', 8),
('Joviânia', 8),
('Jussara', 8),
('Lagoa Santa', 8),
('Leopoldo de Bulhões', 8),
('Luziânia', 8),
('Mairipotaba', 8),
('Mambaí', 8),
('Mara Rosa', 8),
('Marzagão', 8),
('Matrinchã', 8),
('Maurilândia', 8),
('Mimoso de Goiás', 8),
('Minaçu', 8),
('Mineiros', 8),
('Moiporá', 8),
('Monte Alegre de Goiás', 8),
('Montes Claros de Goiás', 8),
('Montividiu', 8),
('Montividiu do Norte', 8),
('Morrinhos', 8),
('Morro Agudo de Goiás', 8),
('Mossâmedes', 8),
('Mozarlândia', 8),
('Mundo Novo', 8),
('Mutunópolis', 8),
('Nazário', 8),
('Nerópolis', 8),
('Niquelândia', 8),
('Nova América', 8),
('Nova Aurora', 8),
('Nova Crixás', 8),
('Nova Glória', 8),
('Nova Iguaçu de Goiás', 8),
('Nova Roma', 8),
('Nova Veneza', 8),
('Novo Brasil', 8),
('Novo Gama', 8),
('Novo Planalto', 8),
('Orizona', 8),
('Ouro Verde de Goiás', 8),
('Ouvidor', 8),
('Padre Bernardo', 8),
('Palestina de Goiás', 8),
('Palmeiras de Goiás', 8),
('Palmelo', 8),
('Palminópolis', 8),
('Panamá', 8),
('Paranaiguara', 8),
('Paraúna', 8),
('Perolândia', 8),
('Petrolina de Goiás', 8),
('Pilar de Goiás', 8),
('Piracanjuba', 8),
('Piranhas', 8),
('Pirenópolis', 8),
('Pires do Rio', 8),
('Planaltina', 8),
('Pontalina', 8),
('Porangatu', 8),
('Porteirão', 8),
('Portelândia', 8),
('Posse', 8),
('Professor Jamil', 8),
('Quirinópolis', 8),
('Rialma', 8),
('Rianápolis', 8),
('Rio Quente', 8),
('Rio Verde', 8),
('Rubiataba', 8),
('Sanclerlândia', 8),
('Santa Bárbara de Goiás', 8),
('Santa Cruz de Goiás', 8),
('Santa Fé de Goiás', 8),
('Santa Helena de Goiás', 8),
('Santa Isabel', 8),
('Santa Rita do Araguaia', 8),
('Santa Rita do Novo Destino', 8),
('Santa Rosa de Goiás', 8),
('Santa Tereza de Goiás', 8),
('Santa Terezinha de Goiás', 8),
('Santo Antônio da Barra', 8),
('Santo Antônio de Goiás', 8),
('Santo Antônio do Descoberto', 8),
('São Domingos', 8),
('São Francisco de Goiás', 8),
('São João d\'Aliança', 8),
('São João da Paraúna', 8),
('São Luís de Montes Belos', 8),
('São Luíz do Norte', 8),
('São Miguel do Araguaia', 8),
('São Miguel do Passa Quatro', 8),
('São Patrício', 8),
('São Simão', 8),
('Senador Canedo', 8),
('Serranópolis', 8),
('Silvânia', 8),
('Simolândia', 8),
('Sítio d\'Abadia', 8),
('Taquaral de Goiás', 8),
('Teresina de Goiás', 8),
('Terezópolis de Goiás', 8),
('Três Ranchos', 8),
('Trindade', 8),
('Trombas', 8),
('Turvânia', 8),
('Turvelândia', 8),
('Uirapuru', 8),
('Uruaçu', 8),
('Uruana', 8),
('Urutaí', 8),
('Valparaíso de Goiás', 8),
('Varjão', 8),
('Vianópolis', 8),
('Vicentinópolis', 8),
('Vila Boa', 8),
('Vila Propício', 8);

-- Inserir dados na tabela TipoSituacao
INSERT INTO tipo_situacao (tipo) VALUES ('Estado');
INSERT INTO tipo_situacao (tipo) VALUES ('Ação');

-- Inserir dados na tabela Situacao
INSERT INTO situacao (situacao, tipo_situacao_id) VALUES ('Logado', 1);
INSERT INTO situacao (situacao, tipo_situacao_id) VALUES ('Deslogado', 1);
INSERT INTO situacao (situacao, tipo_situacao_id) VALUES ('Ativo', 1);
INSERT INTO situacao (situacao, tipo_situacao_id) VALUES ('Desativo', 1);
INSERT INTO situacao (situacao, tipo_situacao_id) VALUES ('Aberto', 1);
INSERT INTO situacao (situacao, tipo_situacao_id) VALUES ('Cumprida', 1);
INSERT INTO situacao (situacao, tipo_situacao_id) VALUES ('Recusada', 1);

INSERT INTO usuario(nome,email,senha) VALUES ('Davi Silva','davirodrigues0506@gmail.com',AES_ENCRYPT('12341234','chave'));

INSERT INTO tipo_atividade(tipo) VALUES
('Multirão de vacina'),
('Entrega de alimentos'),
('Limpeza');

INSERT INTO atividade(nome,hora_comeco,hora_final,descricao,tipo_atividade_id) VALUES
('teste01','10:10:10','11:11:11','TESTE TESTE TESTE TESTE TESTE TESTE TESTE TESTE',1),
('teste02','10:10:10','11:11:11','TESTE TESTE TESTE TESTE TESTE TESTE TESTE TESTE',1),
('teste03','10:10:10','11:11:11','TESTE TESTE TESTE TESTE TESTE TESTE TESTE TESTE',2),
('teste04','10:10:10','11:11:11','TESTE TESTE TESTE TESTE TESTE TESTE TESTE TESTE',2),
('teste05','10:10:10','11:11:11','TESTE TESTE TESTE TESTE TESTE TESTE TESTE TESTE',3);

INSERT calendario()